import streamlit as st

def get_label(label_key):
    labels = {
        'en': {
            'title': "🧹 Data Cleaner App",
            'data_overview': "Data Overview",
            'missing_data': "Missing Data",
            'duplicates': "Duplicates",
            'format_fixing': "Format Fixing",
            'categorical_data': "Categorical Data",
            'error_correction_tab': "Error Correction",
            'text_parsing_tab': "Text Parsing",
            'type_conversion_tab': "Type Conversion",
            'column_operations_tab': "Column Operations",
            'noisy_data_tab': "Noisy Data",
            'reshape_data_tab': "Reshape Data",
            'unstructured_data_tab': "Unstructured Data",
            'cleaning_history_tab': "Cleaning History",
            'fix_inconsistent_formats': "Fix Inconsistent Formats",
            'select_column_to_fix_format': "Select column to fix format",
            'select_format_type': "Select format type",
            'date': "Date",
            'phone_number': "Phone Number",
            'currency': "Currency",
            # General
            'apply': "Apply",
            'error_generic': "Error: {error}",
            'please_upload': "Please upload a CSV file first.",
            # Overview
            'data_overview': "Data Overview",
            'basic_statistics': "Basic Statistics",
            'data_types': "Data Types",
            'missing_values': "Missing Values",
            'sample_data': "Sample Data",
            'shape_of_data': "Shape of Data",
            'rows_cols': "Rows: {rows}, Columns: {cols}",
            'no_data_display': "No data available for display.",
            # Missing Data
            'handle_missing_data': "Handle Missing Data",
            'missing_values_count': "Missing Values Count:",
            'choose_option_missing': "Choose a method to handle missing data:",
            'drop_rows': "Drop Rows",
            'impute_values': "Impute Values",
            'flag_missing': "Flag Missing",
            'enter_value_impute': "Enter value for imputing missing data:",
            'dropped_rows': "Rows with missing values were dropped.",
            'imputed_values': "Missing values were imputed with '{value}'.",
            'please_enter_value': "Please enter a value for imputation.",
            'flagged_missing': "Missing values were flagged.",
            'cleaned_data': "Cleaned Data:",
            # Duplicates
            'remove_duplicates': "Remove Duplicates",
            'remove_exact_duplicates': "Remove Exact Duplicates",
            'removed_exact_duplicates': "Removed {count} exact duplicates.",
            'remove_fuzzy_duplicates': "Remove Fuzzy Duplicates",
            'fuzzy_required': "Fuzzy matching requires the 'thefuzz' library. Install it with 'pip install thefuzz python-Levenshtein' and restart the app.",
            'select_column_fuzzy': "Select column for fuzzy matching",
            'set_similarity_threshold': "Set similarity threshold",
            'removed_fuzzy_duplicates': "Removed {count} duplicates based on fuzzy matching.",
            'no_data_remove_duplicates': "No data available to remove duplicates.",
            # Categorical
            'column_not_exist': "Column '{column}' does not exist in the DataFrame.",
            'standardized_column': "Column '{column}' standardized successfully.",
            # Formatting
            'unsupported_format_type': "Unsupported format type. Choose 'date', 'phone' or 'currency'.",
            'select_column_to_fix_format_tooltip': "Select the column whose data format you want to correct.",
            'select_format_type_tooltip': "Choose the type of data format (Date, Phone Number, Currency) to apply.",
            'fix_format_button': "Fix Format",
            'fixed_format_action': "Fixed {format_type} format in column '{column}'",
            'format_fixed_success': "Format fixed successfully for column '{column}'.",
            # Error Correction
            'error_correction': "Error Correction",
            'data_issues_detection': "Data Issues Detection",
            'no_obvious_issues': "No obvious issues detected in column names and values.",
            'correct_data_errors': "Correct Data Errors",
            'select_correction_method': "Select correction method",
            'correct_outliers': "Correct Outliers (Z-score method)",
            'fix_negative_values': "Fix Negative Values",
            'cap_percentile': "Cap Values at Percentile Limits",
            'no_numeric_outlier': "No numeric columns found for outlier detection.",
            'select_columns_outliers': "Select columns for outlier detection",
            'zscore_threshold': "Z-score threshold",
            'detect_fix_outliers': "Detect and Fix Outliers",
            'found_outliers': "Found {count} outliers in column '{col}'",
            'replaced_outliers_action': "Replaced {count} outliers in '{col}' with median ({median})",
            'outliers_replaced': "Outliers replaced with median!",
            'no_outliers_found': "No outliers found with the current threshold.",
            'no_numeric_columns': "No numeric columns found.",
            'select_columns_negative': "Select columns to fix negative values",
            'how_fix_negative': "How to fix negative values",
            'set_zero': "Set to Zero",
            'set_abs': "Set to Absolute Value",
            'remove_rows': "Remove Rows",
            'set_negative_zero': "Set {count} negative values to zero in '{col}'",
            'set_negative_abs': "Converted {count} negative values to absolute in '{col}'",
            'removed_negative_rows': "Removed {count} rows with negative values in '{col}'",
            'negative_fixed': "Negative values fixed!",
            'no_negative_found': "No negative values found in the selected columns.",
            'select_columns_cap': "Select columns to cap",
            'lower_percentile': "Lower Percentile Limit",
            'upper_percentile': "Upper Percentile Limit",
            'cap_values': "Cap Values",
            'capped_values': "Capped values in '{col}' between {lower}th and {upper}th percentile",
            'below_limit': " ({count} values below the limit)",
            'above_limit': " ({count} values above the limit)",
            'values_capped': "Values were capped at the specified percentile limits!",
            'no_values_outside': "No values found outside the specified limits.",
            'apply_general_error_correction': "Apply General Error Correction",
            'general_error_applied': "General error correction applied!",
            'corrected_outliers_action': "Corrected outliers in column '{column}' with median {median}",
            'corrected_outliers_report': "Corrected outliers in column '{column}'",
            'replaced_with_median': "Replaced with median",
            'errors_corrected': "Errors corrected in the dataset.",
            'impossible_age': "Column '{col}' contains impossible age values",
            'impossible_pct': "Column '{col}' contains percentages outside the range 0-100",
            # Column Operations
            'column_operations': "Column Operations",
            'select_operation': "Select operation",
            'merge_columns': "Merge Columns",
            'split_column': "Split Column",
            'select_first_column_merge': "Select first column to merge",
            'select_second_column_merge': "Select second column to merge",
            'enter_new_column_name': "Enter new column name",
            'enter_separator': "Enter separator (default is space)",
            'merge': "Merge",
            'columns_merged': "Columns '{col1}' and '{col2}' merged into '{new_col}'.",
            'columns_not_exist': "One or both columns '{col1}' and '{col2}' do not exist in the DataFrame.",
            'select_column_split': "Select column to split",
            'enter_new_col1_name': "Enter name for new column 1",
            'enter_new_col2_name': "Enter name for new column 2",
            'split': "Split",
            'column_split': "Column '{col}' split into '{new_col1}' and '{new_col2}'.",
            # Noisy Data
            'noisy_data_cleaned': "Noise in the data was successfully removed!",
            # Reshape
            'reshape_data': "Reshape Data",
            'select_reshape_operation': "Select reshape operation",
            'pivot': "Pivot",
            'melt': "Melt",
            'transpose': "Transpose",
            'select_index_column': "Select column as index",
            'select_columns_column': "Select column for columns",
            'select_values_column': "Select column for values",
            'pivot_data': "Pivot Data",
            'data_pivoted': "Data was successfully reshaped with pivot!",
            'select_id_vars': "Select identifier variables",
            'select_value_vars': "Select value variables",
            'melt_data': "Melt Data",
            'data_melted': "Data was successfully reshaped with melt!",
            'transpose_data': "Transpose Data",
            'data_transposed': "Data was successfully transposed!",
            'please_upload_reshape': "Please upload a CSV file to reshape data.",
            # Text Parsing
            'text_parsing': "Text Parsing",
            'select_parsing_option': "Select parsing option",
            'split_full_names': "Split Full Names",
            'extract_keywords': "Extract Keywords",
            'clean_text_column': "Clean Text Column",
            'parse_dates': "Parse Dates",
            'no_text_columns': "No text columns found in the dataset.",
            'select_column_full_names': "Select column with full names",
            'split_names': "Split Names",
            'split_names_success': "Names successfully split from '{col}'",
            'first_name_col': "First Name",
            'last_name_col': "Last Name",
            'split_full_names_action': "Full names in column '{col}' split into 'First Name' and 'Last Name'",
            'select_text_column': "Select text column",
            'enter_keywords': "Enter keywords (separated by comma)",
            'extract_keywords_btn': "Extract Keywords",
            'extract_keywords_success': "Keywords successfully extracted from '{col}'",
            'extracted_keywords_action': "Keywords extracted from column '{col}' to '{col}_keywords'",
            'select_text_column_clean': "Select text column for cleaning",
            'clean_text_btn': "Clean Text",
            'clean_text_success': "Text successfully cleaned in '{col}'",
            'cleaned_text_action': "Text in column '{col}' cleaned by removing special characters and extra spaces",
            'select_column_dates': "Select column with dates",
            'select_date_format': "Select date format",
            'custom': "Custom",
            'enter_custom_date_format': "Enter custom date format (e.g. %Y-%m-%d)",
            'parse_dates_btn': "Parse Dates",
            'parse_dates_success': "Dates successfully parsed in '{col}'",
            'parsed_dates_action': "Dates in column '{col}' parsed with format '{fmt}'",
            # Type Conversion
            'converted_to_numeric': "Columns converted to numeric.",
            'converted_to_datetime': "Columns converted to date/time.",
            'converted_to_string': "Columns converted to text.",
            # Unstructured Data
            'unstructured_data_cleaning': "Cleaning Unstructured Data",
            'clean_data_btn': "Clean Data",
            'data_cleaned_success': "Data successfully cleaned!",
            'download_cleaned_data': "Download cleaned data",

            # New app UI labels
            'app_description': "A comprehensive tool for cleaning and preprocessing your data for analysis",
            'upload': "Upload Data",
            'choose_file': "Choose a CSV file",
            'reset': "Reset Data",
            'reset_tooltip': "Reset to the original uploaded data",
            'reset_success': "Data has been reset to original state",
            'success_loaded': "Successfully loaded {filename}",
            'error': "Error: {error}",
            'download': "Download Cleaned Data",
            'download_csv': "Download as CSV",
            'file_info': "File Information",
            'filename': "Filename",
            'dimensions': "Dimensions",
            'rows': "rows",
            'columns': "columns",
            'export_options': "Export Options",
            'welcome': "Welcome to Data Cleaner",
            'upload_instruction': "Upload a CSV file to get started with data cleaning",
            'app_features': "Features",
            'feature_overview': "Analyze data shape, types, and summary statistics",
            'feature_missing': "Handle missing data using various strategies",
            'feature_duplicates': "Remove exact and fuzzy duplicates",
            'feature_format': "Standardize date, currency, and phone number formats",
            'feature_more': "And much more!",
            'getting_started': "Getting Started",
            'getting_started_text': "Upload a CSV file using the sidebar, then use the tabs to clean your data in different ways. Your cleaning history will be recorded.",
            'standardize': "Standardize"
        },
        'el': {
            'title': "🧹 Εφαρμογή Καθαρισμού Δεδομένων",
            'data_overview': "Επισκόπηση Δεδομένων",
            'missing_data': "Ελλιπή Δεδομένα",
            'duplicates': "Διπλότυπα",
            'format_fixing': "Διόρθωση Μορφοποίησης",
            'categorical_data': "Κατηγορικά Δεδομένα",
            'error_correction_tab': "Διόρθωση Σφαλμάτων",
            'text_parsing_tab': "Ανάλυση Κειμένου",
            'type_conversion_tab': "Μετατροπή Τύπου",
            'column_operations_tab': "Ενέργειες Στηλών",
            'noisy_data_tab': "Θορυβώδη Δεδομένα",
            'reshape_data_tab': "Αναδιάταξη Δεδομένων",
            'unstructured_data_tab': "Μη Δομημένα Δεδομένα",
            'cleaning_history_tab': "Ιστορικό Καθαρισμού",
            'fix_inconsistent_formats': "Διόρθωση Ασυνεπών Μορφών",
            'select_column_to_fix_format': "Επιλέξτε στήλη για διόρθωση μορφής",
            'select_format_type': "Επιλέξτε τύπο μορφής",
            'date': "Ημερομηνία",
            'phone_number': "Τηλέφωνο",
            'currency': "Νόμισμα",
            # General
            'apply': "Εφαρμογή",
            'error_generic': "Σφάλμα: {error}",
            'please_upload': "Παρακαλώ ανεβάστε πρώτα ένα αρχείο CSV.",
            # Overview
            'data_overview': "Επισκόπηση Δεδομένων",
            'basic_statistics': "Βασικά Στατιστικά",
            'data_types': "Τύποι Δεδομένων",
            'missing_values': "Ελλιπείς Τιμές",
            'sample_data': "Δείγμα Δεδομένων",
            'shape_of_data': "Διάσταση Δεδομένων",
            'rows_cols': "Γραμμές: {rows}, Στήλες: {cols}",
            'no_data_display': "Δεν υπάρχουν διαθέσιμα δεδομένα για εμφάνιση.",
            # Missing Data
            'handle_missing_data': "Διαχείριση Ελλιπών Δεδομένων",
            'missing_values_count': "Αριθμός Ελλιπών Τιμών:",
            'choose_option_missing': "Επιλέξτε τρόπο διαχείρισης ελλιπών δεδομένων:",
            'drop_rows': "Διαγραφή Γραμμών",
            'impute_values': "Συμπλήρωση Τιμών",
            'flag_missing': "Σημείωση Ελλιπών",
            'enter_value_impute': "Εισάγετε τιμή για συμπλήρωση ελλιπών δεδομένων:",
            'dropped_rows': "Οι γραμμές με ελλιπείς τιμές διαγράφηκαν.",
            'imputed_values': "Οι ελλιπείς τιμές συμπληρώθηκαν με '{value}'.",
            'please_enter_value': "Παρακαλώ εισάγετε μια τιμή για συμπλήρωση.",
            'flagged_missing': "Οι ελλιπείς τιμές σημειώθηκαν.",
            'cleaned_data': "Καθαρισμένα Δεδομένα:",
            # Duplicates
            'remove_duplicates': "Αφαίρεση Διπλοτύπων",
            'remove_exact_duplicates': "Αφαίρεση ακριβών διπλοτύπων",
            'removed_exact_duplicates': "Αφαιρέθηκαν {count} ακριβή διπλότυπα.",
            'remove_fuzzy_duplicates': "Αφαίρεση διπλοτύπων με ασαφή αντιστοίχιση",
            'fuzzy_required': "Η ασαφής αντιστοίχιση απαιτεί τη βιβλιοθήκη 'thefuzz'. Εγκαταστήστε τη με 'pip install thefuzz python-Levenshtein' και επανεκκινήστε την εφαρμογή.",
            'select_column_fuzzy': "Επιλέξτε στήλη για ασαφή αντιστοίχιση",
            'set_similarity_threshold': "Ορίστε το όριο ομοιότητας",
            'removed_fuzzy_duplicates': "Αφαιρέθηκαν {count} διπλότυπα με βάση την ασαφή αντιστοίχιση.",
            'no_data_remove_duplicates': "Δεν υπάρχουν διαθέσιμα δεδομένα για αφαίρεση διπλοτύπων.",
            # Categorical
            'column_not_exist': "Η στήλη '{column}' δεν υπάρχει στο DataFrame.",
            'standardized_column': "Η στήλη '{column}' τυποποιήθηκε επιτυχώς.",
            # Formatting
            'unsupported_format_type': "Μη υποστηριζόμενος τύπος μορφής. Επιλέξτε 'date', 'phone' ή 'currency'.",
            'select_column_to_fix_format_tooltip': "Επιλέξτε τη στήλη των δεδομένων που θέλετε να διορθώσετε.",
            'select_format_type_tooltip': "Επιλέξτε τον τύπο των δεδομένων (Ημερομηνία, Αριθμός Τηλεφώνου, Νόμισμα) που θέλετε να εφαρμόσετε.",
            'fix_format_button': "Διόρθωση Μορφής",
            'fixed_format_action': "Διορθώθηκε η μορφή {format_type} στη στήλη '{column}'",
            'format_fixed_success': "Η μορφή διορθώθηκε επιτυχώς για τη στήλη '{column}'.",
            # Error Correction
            'error_correction': "Διόρθωση Σφαλμάτων",
            'data_issues_detection': "Ανίχνευση Προβλημάτων Δεδομένων",
            'no_obvious_issues': "Δεν εντοπίστηκαν εμφανή προβλήματα στα ονόματα και τις τιμές των στηλών.",
            'correct_data_errors': "Διόρθωση Σφαλμάτων Δεδομένων",
            'select_correction_method': "Επιλέξτε μέθοδο διόρθωσης",
            'correct_outliers': "Διόρθωση Ακραίων Τιμών (μέθοδος Z-score)",
            'fix_negative_values': "Διόρθωση Αρνητικών Τιμών",
            'cap_percentile': "Περιορισμός Τιμών σε Ποσοστιαία Όρια",
            'no_numeric_outlier': "Δεν βρέθηκαν αριθμητικές στήλες για ανίχνευση ακραίων τιμών.",
            'select_columns_outliers': "Επιλέξτε στήλες για έλεγχο ακραίων τιμών",
            'zscore_threshold': "Όριο Z-score",
            'detect_fix_outliers': "Ανίχνευση και Διόρθωση Ακραίων Τιμών",
            'found_outliers': "Βρέθηκαν {count} ακραίες τιμές στη στήλη '{col}'",
            'replaced_outliers_action': "Αντικαταστάθηκαν {count} ακραίες τιμές στη '{col}' με τη διάμεσο ({median})",
            'outliers_replaced': "Οι ακραίες τιμές αντικαταστάθηκαν με τη διάμεσο!",
            'no_outliers_found': "Δεν βρέθηκαν ακραίες τιμές με το τρέχον όριο.",
            'no_numeric_columns': "Δεν βρέθηκαν αριθμητικές στήλες.",
            'select_columns_negative': "Επιλέξτε στήλες για διόρθωση αρνητικών τιμών",
            'how_fix_negative': "Πώς να διορθωθούν οι αρνητικές τιμές",
            'set_zero': "Ορισμός σε Μηδέν",
            'set_abs': "Ορισμός σε Απόλυτη Τιμή",
            'remove_rows': "Αφαίρεση Γραμμών",
            'set_negative_zero': "Ορίστηκαν {count} αρνητικές τιμές σε μηδέν στη '{col}'",
            'set_negative_abs': "Μετατράπηκαν {count} αρνητικές τιμές σε απόλυτες στη '{col}'",
            'removed_negative_rows': "Αφαιρέθηκαν {count} γραμμές με αρνητικές τιμές στη '{col}'",
            'negative_fixed': "Οι αρνητικές τιμές διορθώθηκαν!",
            'no_negative_found': "Δεν βρέθηκαν αρνητικές τιμές στις επιλεγμένες στήλες.",
            'select_columns_cap': "Επιλέξτε στήλες για περιορισμό",
            'lower_percentile': "Κατώτερο Ποσοστιαίο Όριο",
            'upper_percentile': "Ανώτερο Ποσοστιαίο Όριο",
            'cap_values': "Περιορισμός Τιμών",
            'capped_values': "Περιορίστηκαν τιμές στη '{col}' μεταξύ {lower}ου και {upper}ου ποσοστού",
            'below_limit': " ({count} τιμές κάτω από το όριο)",
            'above_limit': " ({count} τιμές πάνω από το όριο)",
            'values_capped': "Οι τιμές περιορίστηκαν στα καθορισμένα ποσοστιαία όρια!",
            'no_values_outside': "Δεν βρέθηκαν τιμές εκτός των καθορισμένων ορίων.",
            'apply_general_error_correction': "Εφαρμογή Γενικής Διόρθωσης Σφαλμάτων",
            'general_error_applied': "Η γενική διόρθωση σφαλματος εφαρμόστηκε!",
            'corrected_outliers_action': "Διορθώθηκαν ακραίες τιμές στη στήλη '{column}' με τη διάμεσο {median}",
            'corrected_outliers_report': "Διορθωμένες ακραίες τιμές στη στήλη '{column}'",
            'replaced_with_median': "Αντικαταστάθηκε με τη διάμεσο",
            'errors_corrected': "Σφάλματα διορθώθηκαν στο σύνολο δεδομένων.",
            'impossible_age': "Η στήλη '{col}' περιέχει αδύνατες τιμές ηλικίας",
            'impossible_pct': "Η στήλη '{col}' περιέχει ποσοστά εκτός της κλίμακας 0-100",
            # Column Operations
            'column_operations': "Ενέργειες Στηλών",
            'select_operation': "Επιλέξτε ενέργεια",
            'merge_columns': "Συγχώνευση Στηλών",
            'split_column': "Διαχωρισμός Στήλης",
            'select_first_column_merge': "Επιλέξτε την πρώτη στήλη για συγχώνευση",
            'select_second_column_merge': "Επιλέξτε τη δεύτερη στήλη για συγχώνευση",
            'enter_new_column_name': "Εισάγετε το όνομα της νέας στήλης",
            'enter_separator': "Εισάγετε διαχωριστικό (προεπιλογή είναι το κενό)",
            'merge': "Συγχώνευση",
            'columns_merged': "Οι στήλες '{col1}' και '{col2}' συγχωνεύθηκαν σε '{new_col}'.",
            'columns_not_exist': "Μία ή και οι δύο στήλες '{col1}' και '{col2}' δεν υπάρχουν στο DataFrame.",
            'select_column_split': "Επιλέξτε στήλη για διαχωρισμό",
            'enter_new_col1_name': "Εισάγετε το όνομα για τη νέα στήλη 1",
            'enter_new_col2_name': "Εισάγετε το όνομα για τη νέα στήλη 2",
            'split': "Διαχωρισμός",
            'column_split': "Η στήλη '{col}' διαχωρίστηκε σε '{new_col1}' και '{new_col2}'.",
            # Noisy Data
            'noisy_data_cleaned': "Ο θόρυβος στα δεδομένα αφαιρέθηκε με επιτυχία!",
            'select_text_columns_to_clean': "Επιλέξτε στήλες κειμένου για καθαρισμό",
            'remove_noise': "Αφαίρεση Θορύβου",
            'removed_noise_action': "Αφαιρέθηκε θόρυβος από τις επιλεγμένες στήλες",
            'please_select_text_column': "Παρακαλώ επιλέξτε τουλάχιστον μία στήλη κειμένου.",

            # Reshape Data
            'reshape_data': "Αναδιάταξη Δεδομένων",
            'select_reshape_operation': "Επιλέξτε λειτουργία αναδιάταξης",
            'pivot': "Περιστροφή (Pivot)",
            'melt': "Τήξη (Melt)",
            'transpose': "Αναστροφή",
            'select_index_column': "Επιλέξτε στήλη ως δείκτη",
            'select_columns_column': "Επιλέξτε στήλη για στήλες",
            'select_values_column': "Επιλέξτε στήλη για τιμές",
            'pivot_data': "Περιστροφή Δεδομένων",
            'data_pivoted': "Τα δεδομένα αναδιατάχθηκαν με επιτυχία με περιστροφή!",
            'select_id_vars': "Επιλέξτε μεταβλητές αναγνώρισης",
            'select_value_vars': "Επιλέξτε μεταβλητές τιμών",
            'melt_data': "Τήξη Δεδομένων",
            'data_melted': "Τα δεδομένα αναδιατάχθηκαν με επιτυχία με τήξη!",
            'transpose_data': "Αναστροφή Δεδομένων",
            'data_transposed': "Τα δεδομένα αναστράφηκαν με επιτυχία!",
            'please_upload_reshape': "Παρακαλώ ανεβάστε ένα αρχείο CSV για αναδιάταξη δεδομένων.",

            # Type Conversion
            'converted_to_numeric': "Οι στήλες μετατράπηκαν σε αριθμητικές.",
            'converted_to_datetime': "Οι στήλες μετατράπηκαν σε ημερομηνία/ώρα.",
            'converted_to_string': "Οι στήλες μετατράπηκαν σε κείμενο.",

            # Unstructured Data
            'unstructured_data_cleaning': "Καθαρισμός Μη Δομημένων Δεδομένων",
            'clean_data_btn': "Καθαρισμός Δεδομένων",
            'data_cleaned_success': "Τα δεδομένα καθαρίστηκαν με επιτυχία!",
            'download_cleaned_data': "Κατέβασμα καθαρισμένων δεδομένων",
            'cleaned_unstructured_data_action': "Καθαρίστηκαν μη δομημένα δεδομένα",

            # New app UI labels
            'app_description': "Ένα ολοκληρωμένο εργαλείο για καθαρισμό και προεπεξεργασία των δεδομένων σας για ανάλυση",
            'upload': "Ανέβασμα Δεδομένων",
            'choose_file': "Επιλέξτε ένα αρχείο CSV",
            'reset': "Επαναφορά Δεδομένων",
            'reset_tooltip': "Επαναφορά στα αρχικά δεδομένα",
            'reset_success': "Τα δεδομένα έχουν επαναφερθεί στην αρχική κατάσταση",
            'success_loaded': "Επιτυχής φόρτωση του {filename}",
            'error': "Σφάλμα: {error}",
            'download': "Κατέβασμα Καθαρισμένων Δεδομένων",
            'download_csv': "Κατέβασμα ως CSV",
            'file_info': "Πληροφορίες Αρχείου",
            'filename': "Όνομα αρχείου",
            'dimensions': "Διαστάσεις",
            'rows': "γραμμές",
            'columns': "στήλες",
            'export_options': "Επιλογές Εξαγωγής",
            'welcome': "Καλώς ήρθατε στο Data Cleaner",
            'upload_instruction': "Ανεβάστε ένα αρχείο CSV για να ξεκινήσετε τον καθαρισμό δεδομένων",
            'app_features': "Χαρακτηριστικά",
            'feature_overview': "Ανάλυση σχήματος δεδομένων, τύπων και στατιστικών στοιχείων",
            'feature_missing': "Διαχείριση ελλιπών δεδομένων με διάφορες στρατηγικές",
            'feature_duplicates': "Αφαίρεση ακριβών και ασαφών διπλοτύπων",
            'feature_format': "Τυποποίηση μορφών ημερομηνίας, νομίσματος και τηλεφωνικών αριθμών",
            'feature_more': "Και πολλά άλλα!",
            'getting_started': "Ξεκινώντας",
            'getting_started_text': "Ανεβάστε ένα αρχείο CSV από την πλαϊνή μπάρα και στη συνέχεια χρησιμοποιήστε τις καρτέλες για να καθαρίσετε τα δεδομένα σας με διάφορους τρόπους. Το ιστορικό καθαρισμού σας θα καταγραφεί.",
            'standardize': "Τυποποίηση"
        }
    }

    try:
        lang = st.session_state.get('language', 'en')
    except Exception:
        lang = 'en'
    
    return labels.get(lang, labels['en']).get(label_key, label_key)
